name: Sync to Copy Repo

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Git
      run: |
        git config --global user.name "vinaypbn  "
        git config --global user.email "vinay.pbn@gmail.com"
      
    - name: Copy file and push to copy repository
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        # Clone the first original repository
        git clone https://${{ secrets.PAT }}@github.com/pbnvinay/original.git
        cp original/original.txt .

        # Clone the first original repository
        git clone https://${{ secrets.PAT }}@github.com/pbnvinay/original1.git
        cp original1/orginal1.txt .

    - name: Combine files
      run: |
        # Combine contents of original files
        cat original.txt original1.txt > combined.txt
  
    - name: Push to copy repository
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        # Clone the copy repository
        git clone https://${{ secrets.PAT }}@github.com/pbnvinay/copy.git
        
        # Move combined file to copy repository
        mv combined.txt copy/copy.txt
        
        # Change to the copy repository directory
        cd copy
        
        # Commit and push changes to the copy repository
        git add copy.txt
        git commit -m "Sync changes from original repository"
        git push origin main
